version: "3"
services:
  web:
    depends_on:
      - postgres_service
    build:
      context: .
      dockerfile: Dockerfile
    image: notes  #replace with your image tag
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && chmod +x /app/staticfiles.sh && sh /app/migrate.sh && /app/staticfiles.sh && /app/entrypoint.sh"
    volumes:
       - staticfiles:/app/staticfiles/
  postgres_service:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  staticfiles:
      external: true
  postgres_data: